[webservers]

node1 ansible_host=3.1.49.108 ansible_user=ubuntu ansible_ssh_private_key_file=/home/divyapm2510/ansible/ansiblekey.pem
node2 ansible_host=13.215.193.233 ansible_user=ubuntu ansible_ssh_private_key_file=/home/divyapm2510/ansible/ansiblekey.pem
